Rails/MusicApp/music_app/config/routes.rb
Rails.application.routes.draw do

  resources :users, except: [:index] do
    resources :bands, except: [:show]
    member do
      get '/awaiting_auth', to: 'users#awaiting_auth'
      get '/resend_auth', to: 'users#resend_auth_email'
      get '/authenticate', to: 'users#authenticate'
      post '/authenticate', to: 'users#confirm_auth'
    end
  end

  controller :sessions do
    get '/login', to: 'sessions#new', as: 'login'
    post '/login', to: 'sessions#create'
    delete '/logout', to: 'sessions#destroy', as: 'logout'
  end  

  resources :bands, only: [:index, :show] do
    resources :albums, except: [:show, :destroy]

    member do
      get '/users/:user_id/join', to: 'band_memberships#create', as: 'join', param: :band_id
    end

    get '/members', to: 'users#index', as: 'members'
    get '/add_members', to: 'band_memberships#new', as: 'member_add'
    post '/add_members', to: 'band_memberships#invite'
    delete '/member/:member_id', to: 'band_memberships#destroy', as: 'member_leave'

    post '/like', to: 'bands#like', as: 'like'
    delete 'unlike', to: 'bands#unlike', as: 'unlike'
  end

  resources :albums, only: [:show, :destroy] do
    resources :tracks, except: [:show]

    post '/like', to: 'albums#like', as: 'like'
    delete 'unlike', to: 'albums#unlike', as: 'unlike'
  end

  resources :tracks, only: [:show, :destroy] do
    post '/like', to: 'tracks#like', as: 'like'
    delete 'unlike', to: 'tracks#unlike', as: 'unlike'
  end

  root to: 'users#welcome'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Rails/MusicApp/music_app/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint           not null, primary key
#  authenticated   :boolean          default(FALSE)
#  email           :string           not null
#  password_digest :string           not null
#  session_token   :string
#  username        :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#
# Indexes
#
#  index_users_on_email     (email)
#  index_users_on_username  (username)
#
class User < ApplicationRecord
  validates :username, presence: true, uniqueness: true
  validates :password, length: { minimum: 4 }, allow_nil: true
  validates :email, presence: true
  validates :authenticated, inclusion: [true, false]
  # validates :session_token, presence: true
  validate :passwords_match
  has_secure_password

  after_initialize :set_defaults
  after_initialize :ensure_session_token

  has_many :band_memberships, class_name: :BandMembership, foreign_key: :member_id, dependent: :destroy
  has_many :bands, through: :band_memberships

  has_many :made_likes, class_name: :Like, foreign_key: :liker_id, dependent: :destroy

  has_many :liked_bands, through: :made_likes, source: :likeable, source_type: :Band
  has_many :liked_albums, through: :made_likes, source: :likeable, source_type: :Album
  has_many :liked_tracks, through: :made_likes, source: :likeable, source_type: :Track

  def self.find_by_credentials(email, password)
    ret = User.find_by(email: email)
    return nil if ret.nil?

    ret.is_password?(password) ? ret : nil
  end

  def self.generate_session_token
    SecureRandom.urlsafe_base64(16)
  end

  def password=(pw)
    @password = pw
    self.password_digest = BCrypt::Password.create(pw)
  end
  
  def password
    @password
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def passwords_match
    self.password == self.password_confirmation
  end
  
  def reset_session_token
    self.session_token = self.class.generate_session_token
    self.save!
    self.session_token
  end
  
  def in_the_band?(band_or_album)
    if band_or_album.class == Album
      band = band_or_album.band
    else
      band = band_or_album
    end

    band.has_member?(self)
  end
  
  def authenticated?
    self.authenticated
  end
  
  private
  
  def ensure_session_token
    self.session_token ||= self.class.generate_session_token
  end
  
  def set_defaults
    self.authenticated ||= false
  end
  
end

Rails/MusicApp/music_app/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, only: [:show, :edit, :update, :destroy, :confirm_auth, :awaiting_auth, :resend_auth_email]
  before_action :require_any_logged_in, only: [:show, :edit, :update, :destroy]
  before_action :require_this_logged_in, only: [:show, :edit, :update, :destroy]
  before_action :require_logged_out, only: [:new, :create]

  def welcome
    if current_user
      redirect_to user_path(current_user)
    else
      redirect_to login_path
    end
  end

  def index
    if params[:band_id]
      @band = Band.find(params[:band_id])
      @users = @band.members
    else
      @users = User.all
    end
  end

  def show

  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    
    if @user.save
      UserMailer.signed_up(@user).deliver_later
      redirect_to awaiting_auth_user_path(@user), notice: "check your e mail"
    else
      render :new
    end
  end

  def awaiting_auth
    
  end
  
  def resend_auth_email
    UserMailer.signed_up(@user).deliver_later
    redirect_to awaiting_auth_user_path(@user), notice: "check your e mail"
  end
  
  def authenticate

  end

  def confirm_auth
      @user.authenticated = true
      if @user.save
        login!(@user)
        redirect_to root_path, notice: "Welcome!"
      else
        # something didn't work
        UserMailer.signed_up(@user).deliver_later
        redirect_to awaiting_auth_user_path(@user), notice: "check your e mail AGAIN"
      end
  end
  
  def edit

  end

  def update
    if @user.save(user_params)
      redirect_to root_path, notice: "edited successfully"
    else
      render :edit
    end
  end

  def destroy
    if @user.destroy
      redirect_to root_path, notice: "destroyed user"
    else
      redirect_to root_path, notice: "user not destroyed"
    end
  end

  private

  def find_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end
  
end

Rails/MusicApp/music_app/app/helpers/user_helper.rb
module UserHelper
end

Rails/MusicApp/music_app/app/views/users/_form.html.erb
<div class="app-form" id="signup-form">
  <%= form_with model: user, local: true do |f| %>
    <%= render_errors(@user) %>

    <div class="fields">
      <%= f.label :username %>
      <%= f.text_field :username %>
    </div>

    <div class="fields">
      <%= f.label :email %>
      <%= f.text_field :email %>
    </div>

    <div class="fields">
      <%= f.label :password %>
      <%= f.password_field :password %>
    </div>

    <div class="fields">
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation %>
    </div>

    <div class="actions">
      <%= f.submit "Sign Up", class: "button", style: 'font-size: 18px; font-weight: 100' %>
    </div>
    
  <% end %>
</div>

Rails/MusicApp/music_app/app/views/users/authenticate.html.erb
<h2 class="body-content-main-header" id="login-header">Verify Credentials</h2>

<div class="app-form" id="authenticate-form">
  <%= form_with do %>

    <div class="fields">
      <%= label_tag :email %>
      <%= text_field_tag :email %>
    </div>

    <div class="fields">
      <%= label_tag :password %>
      <%= password_field_tag :password %>
    </div>

    <div class="actions">
      <%= submit_tag "Authenticate", class: "button", style: 'font-size: 18px; font-weight: 100' %>
    </div>
  <% end %>
</div>

Rails/MusicApp/music_app/app/views/users/awaiting_auth.html.erb
<h1>check email</h1>

<%= link_to 'Resend Email', resend_auth_user_path(@user), class: "button" %>

Rails/MusicApp/music_app/app/views/users/edit.html.erb
<h2>Edit user</h2>

<%= render 'form', user: @user %>

Rails/MusicApp/music_app/app/views/users/index.html.erb
<h2 class="body-content-main-header"><%= @band.name %></h2>

<h3 class="body-content-sub-header">Members</h3>
<div class="content-grid" id="band-index">
  <% @users.each do |user| %>
      <%= link_to user.username, user_path(user), class: "grid-item content-button", id: "user-link" %>
  <% end %>
</div>

<h3 class="body-content-links-header">Links</h3>
<div class="content-grid resource-links" id="member-index-links">
  <%# link_to "Invite Member", .........................., class: "button" %>
  <%= link_to "Back to #{@band.name}", band_path(@band), class: "button" %>
</div>

Rails/MusicApp/music_app/app/views/users/new.html.erb
<h2 class="body-content-main-header" id="signup-header">Add a user</h2>

<%= render 'form', user: @user %>

Rails/MusicApp/music_app/app/views/users/show.html.erb
<h2 class="body-content-main-header"><%= @user.username %></h2>

<div class="content-grid" id="album-index">
  <%= link_to 'Your Bands', user_bands_path(@user), class: "grid-item content-button", id: "user-bands-link" %>
  <%# link_to 'Your Content', ..........................., class: "grid-item content-button", id: "user-content-link" %>
</div>

<h3 class="body-content-links-header">Links</h3>
<div class="content-grid resource-links" id="band-links">
  <%= link_to "Add Band", new_user_band_path(@user), class: "button" %>
  <%= link_to "All Bands", bands_path, class: "button" %>
</div>