Rails/99CatsProject/NinetyNineCats/config/routes.rb
Rails.application.routes.draw do
  resources :users do
    resources :rental_requests, only: [:index, :new]
  end

  resources :cats do
    resources :rental_requests, only: [:index, :new]
  end

  resources :rental_requests, except: [:index] do
    patch '/approve' => 'rental_requests#approve', as: 'approve'
    patch '/deny' => 'rental_requests#deny', as: 'deny'
  end

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
  
  root to: 'cats#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Rails/99CatsProject/NinetyNineCats/app/models/cat.rb
require 'action_view'

# == Schema Information
#
# Table name: cats
#
#  id          :bigint           not null, primary key
#  birth_date  :date             not null
#  color       :string           not null
#  description :text             not null
#  name        :string           not null
#  sex         :string(1)        not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
class Cat < ApplicationRecord
  include ActionView::Helpers::DateHelper

  CAT_COLORS = ['black', 'brown', 'orange', 'gray']

  validates :birth_date, :color, :name, :sex, :description, presence: true
  validates :color, inclusion: CAT_COLORS
  validates :sex, inclusion: ['M', 'F']

  has_many :rental_requests, dependent: :destroy
  has_many :users, through: :rental_requests

  def age
    distance_of_time_in_words(self.birth_date, Time.now)
  end
  
end

Rails/99CatsProject/NinetyNineCats/app/models/rental_request.rb
# == Schema Information
#
# Table name: rental_requests
#
#  id         :bigint           not null, primary key
#  end_date   :date             not null
#  start_date :date             not null
#  status     :string           default("PENDING"), not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  cat_id     :bigint
#  user_id    :bigint
#
# Indexes
#
#  index_rental_requests_on_cat_id   (cat_id)
#  index_rental_requests_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (cat_id => cats.id)
#  fk_rails_...  (user_id => users.id)
#
class RentalRequest < ApplicationRecord
  validates :end_date, :start_date, :status, presence: true
  validate :end_date_after_start_date
  validate :cat_is_available

  belongs_to :cat
  belongs_to :user

  def pending?
    self.status == 'PENDING'
  end
  

  def approve!
    ActiveRecord::Base.transaction do
      self.update(status: 'APPROVED')
  
      self.overlapping_pending_requests.each { |req| req.deny! }
    end
  end
  
  def deny!
    self.update(status: 'DENIED')
  end

  def end_date_after_start_date
    unless self.end_date >= self.start_date
      errors.add(:end_date, "End Date must be on or after Start Date")
    end
  end
  
  def cat_is_available
    if self.id.nil? && ! self.overlapping_approved_requests.empty?
      errors.add(:cat_id, "This cat is not available for the requested period")
    end
  end  

  def overlapping_requests
    RentalRequest
      .where(cat_id: cat_id)
      .where(
        "? < start_date and ? > start_date OR ? BETWEEN start_date and end_date", 
        self.start_date, 
        self.end_date,
        self.start_date
      )
      .where.not(id: self.id)
  end

  def overlapping_approved_requests
    overlapping_requests.where(status: 'APPROVED')
  end
  
  
  def overlapping_pending_requests
    overlapping_requests.where(status: 'PENDING')
  end
  
end

Rails/99CatsProject/NinetyNineCats/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :bigint           not null, primary key
#  email      :string
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class User < ApplicationRecord
  validates :name, :email, presence: :true
  validates :email, uniqueness: true

  has_many :rental_requests, dependent: :destroy
  has_many :cats, through: :rental_requests
end

Rails/99CatsProject/NinetyNineCats/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_user

  def set_user
    if session[:user_id]
      @curUser = User.find(session[:user_id])
    else
      @curUser = nil
    end
  end
end

Rails/99CatsProject/NinetyNineCats/app/controllers/cats_controller.rb
class CatsController < ApplicationController
  before_action :find_cat, only: [:show, :edit, :update, :destroy]

  def index
    @cats = Cat.all
  end

  def show
    @rentals = RentalRequest.where(cat_id: @cat.id).order(:start_date)
  end

  def new
    @cat = Cat.new    
  end

  def create
    @cat = Cat.new(cat_params)

    if @cat.save
      redirect_to cats_path
    else
      render :new
    end
  end

  def edit
    
  end

  def update
    if @cat.save(cat_params)
      redirect_to cat_path(@cat)
    else
      render :edit
    end
  end
  
  def destroy
    if @cat.destroy
      redirect_to root_path, notice: "Cat successfully destroyed"
    else
      redirect_to cat_path(@cat)
    end
  end
  
  private
  
  def find_cat
    @cat = Cat.find(params[:id])
  end
  
  def cat_params
    params.require(:cat).permit(:name, :color, :birth_date, :sex, :description)
  end
  
end

Rails/99CatsProject/NinetyNineCats/app/controllers/rental_requests_controller.rb
class RentalRequestsController < ApplicationController

  def index
    if params[:cat_id]
      @rentals = RentalRequest.where(cat_id: params[:cat_id])
      @subject = Cat.find(params[:cat_id])
    elsif params[:user_id]
      @rentals = RentalRequest.where(user_id: params[:user_id])
      @subject = User.find(params[:user_id])
    else
      redirect_to root_path, notice: "Something's wrong"
    end
  end

  def new
    if nobody_logged_in? || making_request_for_wrong_user?
      redirect_to login_path, notice: "You must be logged in to rent a cat!"
    end

    @rq = RentalRequest.new
    @cat_id = params[:cat_id] # might be nil
    @user_id = session[:user_id]
  end
  
  def create
    @rq = RentalRequest.new(request_params)

    if @rq.save
      redirect_to cat_path(id: @rq.cat_id), notice: "Request submitted"
    else
      render 'new'
    end
  end

  def approve
    @toApprove = RentalRequest.find(params[:rental_request_id])
    @toApprove.approve!

    redirect_to cat_path(id: @toApprove.cat_id)
  end
  
  def deny
    @toDeny = RentalRequest.find(params[:rental_request_id])
    @toDeny.deny!

    redirect_to cat_path(id: @toDeny.cat_id)
  end
  
  private

  def request_params
    params.require(:rental_request).permit(:user_id, :cat_id, :start_date, :end_date)
  end

  def nobody_logged_in?
    # returns true if nobody is logged in
    session[:user_id].nil?
  end

  def making_request_for_wrong_user?
    params[:user_id] && (params[:user_id].to_i != session[:user_id])
  end
  
  
  
end

Rails/99CatsProject/NinetyNineCats/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    redirect_to new_user_path if User.none?
    redirect_to user_path(id: session[:user_id]) if session[:user_id]
  end
  
  def create
    user = User.find_by(name: params[:name])
    if user.nil? || user.email != params[:email]
      redirect_to login_url, notice: "No user with those credentials exists"
    else
      session[:user_id] = user.id
      redirect_to root_path, notice: "Successfully Logged In"
    end
  end
  
  def destroy
    session[:user_id] = nil

    redirect_to root_path, notice: "Successfully Logged Out"
  end
  
end

Rails/99CatsProject/NinetyNineCats/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all
  end

  def show

  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @user.save(user_params)
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  def destroy
    if @user.destroy
      redirect_to users_path, notice: "User successfully destroyed"
    else
    end
  end

  private

  def find_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :email)
  end
  
  
end

Rails/99CatsProject/NinetyNineCats/app/helpers/rental_requests_helper.rb
module RentalRequestsHelper
end

Rails/99CatsProject/NinetyNineCats/app/views/rental_requests/_form.html.erb
<div class="app-form">
  <%= form_with model: rq do |f| %>
    <%= f.hidden_field :user_id, value: user_id %>
    <% if cat_id.nil? %>
      <div class="fields">
        <%= f.label :cat_id, "Which cat?" %><br>
        <%= f.collection_select :cat_id, Cat.all, :id, :name, prompt: true %>
      </div>
    <% else %>
      <%= f.hidden_field :cat_id, value: cat_id %>
    <% end %>

    <div class="fields">
      <%= f.label :start_date %><br>
      <%= f.date_field :start_date %>
    </div>

    <div class="fields">
      <%= f.label :end_date %><br>
      <%= f.date_field :end_date %>
    </div>

    <div class="actions">
      <%= f.submit "Request Rental!" %>
    </div>
  <% end %>
</div>

Rails/99CatsProject/NinetyNineCats/app/views/rental_requests/index.html.erb
<h1>Rental Requests for <%= @subject.name %> (<%= @subject.class.to_s %>)</h1>


<% @rentals.each do |rental| %>
  <div class="rental_info">
    <% if @subject.class == Cat %>
      <p>I'm rented from <%= rental.start_date %> to <%= rental.end_date %> (<%= rental.status %>)</p>
    <% else %>
      <p>I'm requesting from <%= rental.start_date %> to <%= rental.end_date %> (<%= rental.status %>)</p>
    <% end %>
  </div>

  <% if rental.status == 'PENDING' %>
    <div class="rental_button">
      <%= button_to 'Approve', rental_request_approve_url(rental), method: :patch %>
      <%= button_to 'Deny', rental_request_deny_url(rental), method: :patch %>
    </div>
  <% end %>
<% end %>

<%= link_to 'Back', "/#{@subject.class.to_s.downcase.pluralize}/#{@subject.id}" %> | <%= link_to 'All Cats', cats_path %>

Rails/99CatsProject/NinetyNineCats/app/views/rental_requests/new.html.erb
<div class="body-content-header">
  <div class="body-content-header-nav">
    <h1>Request a Rental!</h1>
    <%= link_to 'Cancel', root_path %>
  </div>
</div>

<div class="body-content-main">
  <%= render 'form', rq: @rq, cat_id: @cat_id, user_id: @user_id %>
</div>

Rails/99CatsProject/NinetyNineCats/app/views/users/_form.html.erb
<div class="app-form">
  <%= form_with model: user do |f| %>
    <div class="fields">
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>

    <div class="fields">
      <%= f.label :email %>
      <%= f.text_field :email %>
    </div>

    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>
</div>

Rails/99CatsProject/NinetyNineCats/app/views/users/edit.html.erb
<h1>Edit User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Cancel', users_path %>

Rails/99CatsProject/NinetyNineCats/app/views/users/index.html.erb
<h1>All Users</h1>

<ul>
  <% @users.each do |aUser| %>
    <li><%= link_to aUser.name, user_url(aUser) %></li>
  <% end %>
</ul>

<%= link_to 'New User', new_user_url %>

Rails/99CatsProject/NinetyNineCats/app/views/users/new.html.erb
<div class="body-content-header">
  <div class="body-content-header-nav">
    <h1>Sign Up!</h1>
    <%= link_to 'Cancel', root_path %>
  </div>
</div>

<div class="body-content-main">
  <%= render 'form', user: @user %>
</div>

Rails/99CatsProject/NinetyNineCats/app/views/users/show.html.erb
<div class="body-content-header">
  <div class="body-content-header-nav">
    <h1></h1>
    <%= link_to 'All Rental Requests', user_rental_requests_url(@user) %>
    <%= link_to 'Make Rental Request', new_user_rental_request_url(@user) %>
    <%= link_to 'Modify', edit_user_path(@user) %>
    <%= link_to 'Murder', user_path, method: :delete %>
    <%= link_to 'All Users', users_url %>
    <%= link_to 'Cats', cats_url %>
    <%= link_to 'Home', root_path %>
  </div>
</div>

<div class="body-content-main">
  <div class="info-page-info">
    <table>

      <tbody>
        <tr>
          <td>Name:</td>
          <td><%= @user.name %></td>
        </tr>

        <tr>
          <td>Email:</td>
          <td><%= @user.email %></td>
        </tr>

      </tbody>

    </table>
  </div>
  
</div>